#!/usr/bin/env python3
"""Generate a changelog entry from git history and update CHANGELOG.md.

Expects environment variables:
    NEW_VERSION  — the new semver version (e.g. "0.2.0")
    REPO         — GitHub repository in "owner/repo" format
    PREV_TAG     — previous git tag (empty string if first release)
    GITHUB_OUTPUT — path to the GitHub Actions output file
"""

import datetime
import os
import subprocess
from pathlib import Path


def main() -> None:
    new_version = os.environ["NEW_VERSION"]
    repo = os.environ["REPO"]
    prev_tag = os.environ.get("PREV_TAG") or ""

    log_range = "HEAD" if not prev_tag else f"{prev_tag}..HEAD"
    SEP = "\x1f"  # unit separator — safe delimiter
    raw_commits = subprocess.run(
        ["git", "log", f"--pretty=format:%s{SEP}%H", log_range],
        check=True,
        text=True,
        capture_output=True,
    ).stdout.strip().splitlines()

    commits = []
    for line in raw_commits:
        if SEP not in line:
            continue
        subject, sha = line.split(SEP, 1)
        commits.append(
            f"- {subject} [`{sha[:7]}`](https://github.com/{repo}/commit/{sha})"
        )

    if not commits:
        commits.append("- No notable changes recorded.")

    released_on = datetime.datetime.now(datetime.timezone.utc).strftime("%-d %B %Y")

    tag = f"v{new_version}"
    entry = (
        f"#### [{tag}](https://github.com/{repo}/releases/tag/{tag})\n\n"
        f"> {released_on}\n\n"
        + "\n".join(commits)
        + "\n\n"
    )

    # Update CHANGELOG.md
    changelog = Path("CHANGELOG.md")
    content = changelog.read_text().splitlines()
    insert_at = len(content)
    for idx, line in enumerate(content):
        if line.startswith("Generated by"):
            insert_at = idx + 1
            while insert_at < len(content) and content[insert_at].strip() == "":
                insert_at += 1
            break

    new_content = content[:insert_at] + ["", entry.rstrip(), ""] + content[insert_at:]
    changelog.write_text("\n".join(new_content).rstrip() + "\n")

    # Write to GITHUB_OUTPUT
    output_path = os.environ.get("GITHUB_OUTPUT")
    if output_path:
        with open(output_path, "a", encoding="utf-8") as fh:
            fh.write("body<<EOF\n")
            fh.write(entry)
            fh.write("\nEOF\n")


if __name__ == "__main__":
    main()
